// Embeds the canonical Agent Setup fragments as runtime-neutral string
// constants in `src/script-assets.generated.ts`. Runtime TypeScript composes a
// platform common fragment with exactly one agent fragment, so public scripts
// never carry the other agent's implementation.
//
// Run `pnpm --filter @floway-dev/agent-setup run generate-assets` to rewrite
// the generated module; pass `--check` to fail when checked-in output drifts.
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = resolve(HERE, '..');
const GENERATED_PATH = resolve(PACKAGE_ROOT, 'src/script-assets.generated.ts');

const fragments = [
  ['SETUP_BASH_COMMON_OUTPUT', 'installers/bash/common/output.sh'],
  ['SETUP_BASH_COMMON_HELPERS', 'installers/bash/common/helpers.sh'],
  ['SETUP_BASH_COMMON_MAIN', 'installers/bash/common/main.sh'],
  ['SETUP_BASH_CLAUDE', 'installers/bash/claude.sh'],
  ['SETUP_BASH_CODEX', 'installers/bash/codex.sh'],
  ['SETUP_POWERSHELL_COMMON_OUTPUT', 'installers/powershell/common/output.ps1'],
  ['SETUP_POWERSHELL_COMMON_HELPERS', 'installers/powershell/common/helpers.ps1'],
  ['SETUP_POWERSHELL_COMMON_MAIN', 'installers/powershell/common/main.ps1'],
  ['SETUP_POWERSHELL_CLAUDE', 'installers/powershell/claude.ps1'],
  ['SETUP_POWERSHELL_CODEX', 'installers/powershell/codex.ps1'],
] as const;

const sources = await Promise.all(fragments.map(async ([name, file]) => ({
  name,
  file,
  source: await readFile(resolve(PACKAGE_ROOT, file), 'utf8'),
})));
const constants = sources.map(({ name, source }) => `export const ${name} = ${JSON.stringify(source)};`).join('\n\n');
const fileList = sources.map(({ file }) => `// - ${file}`).join('\n');
const expected = `// GENERATED by scripts/generate-assets.ts — do not edit by hand.
//
// Canonical installer fragments embedded verbatim from:
${fileList}
// Regenerate after editing a fragment:
// \`pnpm --filter @floway-dev/agent-setup run generate-assets\`.

${constants}
`;

if (process.argv.includes('--check')) {
  const actual = await readFile(GENERATED_PATH, 'utf8').catch((error: NodeJS.ErrnoException) => {
    // A missing generated file is drift the check should report; any other read
    // failure (permissions, I/O) is a real fault and must propagate.
    if (error.code === 'ENOENT') return null;
    throw error;
  });
  if (actual !== expected) {
    console.error('script-assets.generated.ts is out of date with the canonical installer fragments.');
    console.error('Run: pnpm --filter @floway-dev/agent-setup run generate-assets');
    process.exit(1);
  }
  console.log('script-assets.generated.ts is up to date.');
} else {
  await writeFile(GENERATED_PATH, expected);
  console.log(`Wrote ${GENERATED_PATH}`);
}
