/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | '/dashboard/'
      | '/dashboard/keys/'
      | '/dashboard/models'
      | '/dashboard/performance'
      | '/dashboard/requests/'
      | '/dashboard/requests/[keyId]'
      | '/dashboard/settings'
      | '/dashboard/upstreams/[id]'
      | '/dashboard/upstreams/new/[provider]'
      | '/dashboard/usage'
      | '/dashboard/users'
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/keys/': RouteRecordInfo<
      '/dashboard/keys/',
      '/dashboard/keys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/models': RouteRecordInfo<
      '/dashboard/models',
      '/dashboard/models',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/performance': RouteRecordInfo<
      '/dashboard/performance',
      '/dashboard/performance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/requests/': RouteRecordInfo<
      '/dashboard/requests/',
      '/dashboard/requests',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/requests/[keyId]': RouteRecordInfo<
      '/dashboard/requests/[keyId]',
      '/dashboard/requests/:keyId',
      { keyId: ParamValue<true> },
      { keyId: ParamValue<false> },
      | never
    >,
    '/dashboard/settings': RouteRecordInfo<
      '/dashboard/settings',
      '/dashboard/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/upstreams/[id]': RouteRecordInfo<
      '/dashboard/upstreams/[id]',
      '/dashboard/upstreams/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dashboard/upstreams/new/[provider]': RouteRecordInfo<
      '/dashboard/upstreams/new/[provider]',
      '/dashboard/upstreams/new/:provider',
      { provider: ParamValue<true> },
      { provider: ParamValue<false> },
      | never
    >,
    '/dashboard/usage': RouteRecordInfo<
      '/dashboard/usage',
      '/dashboard/usage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/users': RouteRecordInfo<
      '/dashboard/users',
      '/dashboard/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
        | '/dashboard/'
        | '/dashboard/keys/'
        | '/dashboard/models'
        | '/dashboard/performance'
        | '/dashboard/requests/'
        | '/dashboard/requests/[keyId]'
        | '/dashboard/settings'
        | '/dashboard/upstreams/[id]'
        | '/dashboard/upstreams/new/[provider]'
        | '/dashboard/usage'
        | '/dashboard/users'
      views:
        | 'default'
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
    }
    'src/pages/dashboard/keys/index.vue': {
      routes:
        | '/dashboard/keys/'
      views:
        | never
    }
    'src/pages/dashboard/models.vue': {
      routes:
        | '/dashboard/models'
      views:
        | never
    }
    'src/pages/dashboard/performance.vue': {
      routes:
        | '/dashboard/performance'
      views:
        | never
    }
    'src/pages/dashboard/requests/index.vue': {
      routes:
        | '/dashboard/requests/'
      views:
        | never
    }
    'src/pages/dashboard/requests/[keyId].vue': {
      routes:
        | '/dashboard/requests/[keyId]'
      views:
        | never
    }
    'src/pages/dashboard/settings.vue': {
      routes:
        | '/dashboard/settings'
      views:
        | never
    }
    'src/pages/dashboard/upstreams/[id].vue': {
      routes:
        | '/dashboard/upstreams/[id]'
      views:
        | never
    }
    'src/pages/dashboard/upstreams/new/[provider].vue': {
      routes:
        | '/dashboard/upstreams/new/[provider]'
      views:
        | never
    }
    'src/pages/dashboard/usage.vue': {
      routes:
        | '/dashboard/usage'
      views:
        | never
    }
    'src/pages/dashboard/users.vue': {
      routes:
        | '/dashboard/users'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
