export const PUBLIC_DATA_PLANE_ROUTES = {
  alphaSearch: { method: 'POST', paths: ['/alpha/search', '/v1/alpha/search'] },
  openaiChatCompletions: { method: 'POST', paths: ['/v1/chat/completions', '/chat/completions'] },
  openaiResponses: { method: 'POST', paths: ['/v1/responses', '/responses'] },
  openaiResponsesCompact: { method: 'POST', paths: ['/v1/responses/compact', '/responses/compact'] },
  anthropicMessages: { method: 'POST', paths: ['/v1/messages', '/messages'] },
  anthropicMessagesCountTokens: { method: 'POST', paths: ['/v1/messages/count_tokens', '/messages/count_tokens'] },
  openaiResponsesWebSocket: { method: 'GET', paths: ['/v1/responses', '/responses'] },
  geminiGenerateContentAction: { method: 'POST', paths: ['/v1beta/models/:modelAction{.+}'] },
  codexAlphaSearch: { method: 'POST', paths: ['/azure-api.codex/alpha/search'] },
  codexOpenAIResponses: { method: 'POST', paths: ['/azure-api.codex/responses'] },
  codexOpenAIResponsesCompact: { method: 'POST', paths: ['/azure-api.codex/responses/compact'] },
  codexOpenAIResponsesWebSocket: { method: 'GET', paths: ['/azure-api.codex/responses'] },
  codexOpenAIImagesGenerations: { method: 'POST', paths: ['/azure-api.codex/images/generations'] },
  codexOpenAIImagesEdits: { method: 'POST', paths: ['/azure-api.codex/images/edits'] },
  codexModels: { method: 'GET', paths: ['/azure-api.codex/models'] },
  models: { method: 'GET', paths: ['/v1/models', '/models'] },
  geminiModels: { method: 'GET', paths: ['/v1beta/models'] },
  geminiModel: { method: 'GET', paths: ['/v1beta/models/:modelId{.+}'] },
  openaiEmbeddings: { method: 'POST', paths: ['/v1/embeddings', '/embeddings'] },
  openaiCompletions: { method: 'POST', paths: ['/v1/completions', '/completions'] },
  openaiImagesGenerations: { method: 'POST', paths: ['/v1/images/generations', '/images/generations'] },
  openaiImagesEdits: { method: 'POST', paths: ['/v1/images/edits', '/images/edits'] },
  openaiAudioTranscriptions: { method: 'POST', paths: ['/v1/audio/transcriptions'] },
  cohereV1Rerank: { method: 'POST', paths: ['/v1/rerank'] },
  cohereV2Rerank: { method: 'POST', paths: ['/v2/rerank'] },
  jinaV1Rerank: { method: 'POST', paths: ['/jina/v1/rerank'] },
  voyageV1Rerank: { method: 'POST', paths: ['/voyage/v1/rerank'] },
} as const;

export type PublicDataPlaneRouteId = keyof typeof PUBLIC_DATA_PLANE_ROUTES;
export type PublicDataPlaneRoute = typeof PUBLIC_DATA_PLANE_ROUTES[PublicDataPlaneRouteId];
